# Generated by Django 4.2.4 on 2023-08-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('contract', models.CharField(choices=[('Manut', 'Manutenção'), ('Modern', 'Modernização')], max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=999)),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('renewal_date', models.DateTimeField()),
                ('elevators_qty', models.IntegerField()),
                ('elevators_brand', models.CharField(max_length=30)),
            ],
        ),
    ]
