# Generated by Django 4.2.4 on 2023-08-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract',
            field=models.CharField(choices=[('Manut', 'Manutenção'), ('Modern', 'Modernização')], max_length=6, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='elevators_brand',
            field=models.CharField(max_length=30, verbose_name='Marca dos Elevadores'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='elevators_qty',
            field=models.IntegerField(verbose_name='Quantidade de Elevadores'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='expiration_date',
            field=models.DateTimeField(verbose_name='Data de Término do Contrato'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Valor do Contrato/Mês'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='renewal_date',
            field=models.DateTimeField(verbose_name='Data de Renovação'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=30, verbose_name='Estado'),
        ),
    ]
