# Generated by Django 4.2.4 on 2023-08-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contract',
            field=models.CharField(choices=[('Manutenção', 'Manutenção'), ('Modernização', 'Modernização')], max_length=12, verbose_name='Tipo de Contrato'),
        ),
    ]
