# Generated by Django 4.2.4 on 2023-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='renewal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Renovação'),
        ),
    ]
