# Generated by Django 4.2.4 on 2023-08-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('data_de_inicio', models.DateTimeField()),
                ('vigencia', models.DateTimeField()),
                ('data_de_renovacao', models.DateTimeField()),
                ('marca_dos_equipamentos', models.CharField(choices=[('Atlas', 'Atlas'), ('Otis', 'Otis'), ('Thyessen', 'Thyessen')], max_length=8)),
                ('quantidade_de_elevadores', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ClientePF',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
            bases=('clientes.cliente',),
        ),
        migrations.CreateModel(
            name='ClientePJ',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=100)),
            ],
            bases=('clientes.cliente',),
        ),
    ]
