# Generated by Django 4.2.4 on 2023-10-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254)),
                ('data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ClientePF',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Cliente CPF',
                'verbose_name_plural': 'Clientes CPF',
            },
            bases=('clientes.cliente',),
        ),
        migrations.CreateModel(
            name='ClientePJ',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
            ],
            options={
                'verbose_name': 'Cliente CNPJ',
                'verbose_name_plural': 'Clientes CNPJ',
            },
            bases=('clientes.cliente',),
        ),
    ]
