# Generated by Django 4.2.4 on 2023-09-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_de_criacao',
            new_name='data_de_inicio',
        ),
    ]
