# Generated by Django 4.2.4 on 2023-08-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_de_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_de_renovacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vigencia',
            field=models.DateField(),
        ),
    ]
