# Generated by Django 4.2.4 on 2023-08-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_data_de_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_de_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_de_renovacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vigencia',
            field=models.DateTimeField(),
        ),
    ]
