# Generated by Django 4.2.4 on 2023-09-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_data_de_criacao_cliente_data_de_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_de_renovacao',
            field=models.DateField(null=True, verbose_name='Data de Renovação'),
        ),
    ]
