# Generated by Django 4.2.4 on 2023-09-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_data_de_renovacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_de_renovacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='vigencia',
            field=models.CharField(choices=[('12 meses', '12 meses'), ('24 meses', '24 meses'), ('36 meses', '36 meses'), ('48 meses', '48 meses')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_de_inicio',
            field=models.DateField(auto_now=True, verbose_name='Data de Início'),
        ),
    ]
