# Generated by Django 4.2.4 on 2023-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_data_de_renovacao_cliente_vigencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_de_inicio',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
