# Generated by Django 4.2.4 on 2023-08-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_data_de_inicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientepf',
            options={'verbose_name': 'Cliente CPF', 'verbose_name_plural': 'Clientes CPF'},
        ),
        migrations.AlterModelOptions(
            name='clientepj',
            options={'verbose_name': 'Cliente CNPJ', 'verbose_name_plural': 'Clientes CNPJ'},
        ),
    ]
