# Generated by Django 4.2.4 on 2023-09-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_data_de_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='vigencia',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_de_inicio',
            field=models.DateField(verbose_name='Data de Criação'),
        ),
    ]
