# Generated by Django 4.2.4 on 2023-08-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_clientepf_options_alter_clientepj_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_de_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_de_renovacao',
            field=models.DateField(verbose_name='Data de Renovação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(max_length=30, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vigencia',
            field=models.DateField(verbose_name='Vigência'),
        ),
        migrations.AlterField(
            model_name='clientepf',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientepj',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='clientepj',
            name='razao_social',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
    ]
