# Generated by Django 4.2.4 on 2023-08-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Cliente')),
                ('description', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('deadline', models.CharField(max_length=30, verbose_name='Prazo de execução')),
                ('value', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Valor')),
                ('parcels', models.PositiveIntegerField(blank=True, null=True, verbose_name='Parcelas')),
                ('parcels_value', models.CharField(max_length=30, verbose_name='Valor das Parcelas')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
    ]
