# Generated by Django 4.2.4 on 2023-08-15 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customer_renewal_date'),
        ('budgets', '0002_alter_budget_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.customer', verbose_name='Cliente:'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='deadline',
            field=models.CharField(max_length=30, verbose_name='Prazo de execução:'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Descrição dos serviços a serem executados:'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='parcels',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Parcelas:'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='parcels_value',
            field=models.CharField(max_length=30, verbose_name='Valor das Parcelas:'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Valor:'),
        ),
    ]
