# Generated by Django 4.2.4 on 2023-10-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('vigencia', models.CharField(choices=[('12 meses', '12 meses'), ('24 meses', '24 meses'), ('36 meses', '36 meses'), ('48 meses', '48 meses')], max_length=8, null=True)),
                ('data_de_renovacao', models.DateField(verbose_name='Data de Renovação')),
                ('mes_reajuste', models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], max_length=9)),
                ('marca_dos_elevadores', models.CharField(choices=[('Atlas Schindler', 'Atlas Schindler'), ('Otis', 'Otis'), ('Hyundai', 'Hyundai'), ('Thyessen', 'Thyessen'), ('Villarta', 'Villarta')], max_length=15)),
                ('quantidade_de_elevadores', models.PositiveIntegerField()),
                ('modelo_dos_elevadores', models.CharField(max_length=99)),
                ('observacoes', models.TextField(max_length=999)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente', verbose_name='Cliente')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.tipocontrato')),
            ],
            options={
                'verbose_name': 'Contrato Anual',
                'verbose_name_plural': 'Contratos Anuais',
            },
        ),
    ]
