# Generated by Django 4.2.4 on 2023-08-31 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('vigencia', models.DateField(verbose_name='Vigência')),
                ('data_de_renovacao', models.DateField(verbose_name='Data de Renovação')),
                ('mes_reajuste', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente', verbose_name='Cliente')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.tipocontrato')),
            ],
            options={
                'verbose_name': 'Contrato Anual',
                'verbose_name_plural': 'Contratos Anuais',
            },
        ),
    ]
