# Generated by Django 4.2.4 on 2023-08-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoanual',
            name='mes_reajuste',
            field=models.DateField(verbose_name='Mês de Reajuste'),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='nome',
            field=models.CharField(choices=[('Conservação', 'Conservação'), ('Integral', 'Integral')], max_length=11),
        ),
    ]
