# Generated by Django 4.2.4 on 2023-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_remove_tipocontrato_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontrato',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
