# Generated by Django 4.2.4 on 2023-09-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_tipocontrato_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoanual',
            name='vigencia',
            field=models.CharField(choices=[('12 meses', '12 meses'), ('24 meses', '24 meses'), ('36 meses', '36 meses'), ('48 meses', '48 meses')], max_length=8, null=True),
        ),
    ]
